[package]
name = "kuukiyomu"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1"
serde = { version = "1", features = [ "derive" ] }
procfs = "*"
rmp-serde = "1.3.0"
bincode = "1.3.3"
clap = { version = "4.5.9", features = ["derive"] }
