[repository]
name = "Kuukiyomu"
authors = ["yamabiiko"]
commit_pins = [
    ["918d8340afd652b011b937d29d5eea0be08467f5", "660a03e4dd248ccaf78fec8f09c3e0b75d213d42"]
]

[kuukiyomu]
description = "Session manager for hyprland"
authors = ["yamabiiko"]
output = "build/libkuukiyomu.so"
build = [
	"cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -B build",
	"cmake --build build"
]
