[repository]
name = "Kuukiyomu"
authors = ["yamabiiko"]
commit_pins = [
    ["918d8340afd652b011b937d29d5eea0be08467f5", "1303cf4e9489b2de4e310e3c80f34fc9b28b6626"]
]

[kuukiyomu]
description = "Session manager for hyprland"
authors = ["yamabiiko"]
output = "build/libkuukiyomu.so"
build = [
	"cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -B build",
	"cmake --build build"
]
